# Generated by Django 5.2.3 on 2025-10-10 07:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_alter_abstractsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractsubmission',
            options={'ordering': ['-submitted_on'], 'verbose_name_plural': 'Abstract Submissions'},
        ),
        migrations.AlterModelOptions(
            name='finalregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='visitorregistration',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='abstractsubmission',
            name='main_author',
        ),
        migrations.RemoveField(
            model_name='abstractsubmission',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='abstractsubmission',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='theme',
            field=models.CharField(blank=True, choices=[('Environment, Climate & Sustainability', 'Environment, Climate & Sustainability'), ('Society, Equity, Transformation & Social Work', 'Society, Equity, Transformation & Social Work'), ('Knowledge, Education & Human Development', 'Knowledge, Education & Human Development'), ('Economy, Technology & Social Impact', 'Economy, Technology & Social Impact'), ('Culture, Identity & Globalization', 'Culture, Identity & Globalization'), ('General Social Science and Others', 'General Social Science and Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='abstractsubmission',
            name='FOOD_PREFERENCE',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON VEG')], default='VEG', max_length=20),
        ),
        migrations.AlterField(
            model_name='abstractsubmission',
            name='designation',
            field=models.CharField(choices=[('Student', 'Student'), ('Research Scholar', 'Research Scholar'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Corporate', 'Corporate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalvisitor',
            name='id_proof_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='identity_proofs/'),
        ),
        migrations.AlterField(
            model_name='coauthor',
            name='FOOD_PREFERENCE',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='VEG', max_length=20),
        ),
    ]
